"""
gRPC transport for BloomFL gossip parameter exchange.

Each node runs both a ``GossipServicer`` (server side) and uses a stub
(client side) to contact peers.  The server is non-blocking — it starts
in a background ``ThreadPoolExecutor``-backed gRPC server.

gRPC stubs are generated by running:
    bash scripts/generate_proto.sh

If the generated stubs are missing (e.g. first install), this module
falls back gracefully so that TCP transport still works.
"""
from __future__ import annotations

import logging
from concurrent import futures
from typing import Optional

from bloomfl.transport.base import (
    BaseTransport,
    ExchangeHandler,
    TransportError,
    WirePayload,
)

logger = logging.getLogger(__name__)

# ── Lazy gRPC imports (stubs may not exist yet) ───────────────────────────────

def _import_grpc_deps():
    """Import gRPC and generated stubs; raise ImportError with guidance if missing."""
    try:
        import grpc  # noqa: F401
    except ImportError as exc:
        raise ImportError(
            "grpcio not installed. Run: pip install grpcio grpcio-tools"
        ) from exc
    try:
        from bloomfl.generated import gossip_pb2, gossip_pb2_grpc
    except ImportError as exc:
        raise ImportError(
            "gRPC stubs not generated. Run: bash scripts/generate_proto.sh"
        ) from exc
    return grpc, gossip_pb2, gossip_pb2_grpc


# ── Conversion helpers ────────────────────────────────────────────────────────

def _to_pb(payload: WirePayload, gossip_pb2):
    return gossip_pb2.ParameterMessage(
        node_id=payload.node_id,
        payload=payload.payload,
        nonce=payload.nonce,
        public_key=payload.public_key,
        round=payload.round,
        weight=payload.weight,
        data_hash=payload.data_hash,
    )


def _from_pb(msg) -> WirePayload:
    return WirePayload(
        node_id=msg.node_id,
        payload=msg.payload,
        nonce=msg.nonce,
        public_key=msg.public_key,
        round=msg.round,
        weight=msg.weight,
        data_hash=msg.data_hash,
    )


# ── gRPC Servicer ─────────────────────────────────────────────────────────────

class _GossipServicer:
    """Server-side handler for incoming gRPC ExchangeParameters calls."""

    def __init__(self, handler: ExchangeHandler, gossip_pb2, gossip_pb2_grpc_base):
        self._handler = handler
        self._pb2 = gossip_pb2
        self._base = gossip_pb2_grpc_base  # holds GossipServiceServicer base

    def ExchangeParameters(self, request, context):
        peer_payload = _from_pb(request)
        response = self._handler(peer_payload)
        return _to_pb(response, self._pb2)

    def Ping(self, request, context):
        return self._pb2.PingResponse(node_id=request.node_id, alive=True)


# ── gRPC Transport ────────────────────────────────────────────────────────────

class GRPCTransport(BaseTransport):
    """gRPC-based gossip parameter exchange transport.

    Implements :class:`~bloomfl.transport.base.BaseTransport` using gRPC
    with the ``GossipService`` defined in ``proto/gossip.proto``.
    """

    def __init__(self, max_workers: int = 10) -> None:
        self._max_workers = max_workers
        self._server = None
        self._grpc = None
        self._pb2 = None
        self._pb2_grpc = None
        self._running = False
        self._handler: Optional[ExchangeHandler] = None

    # ── Server ────────────────────────────────────────────────────────────────

    def start_server(
        self,
        host: str,
        port: int,
        handler: ExchangeHandler,
    ) -> None:
        grpc, gossip_pb2, gossip_pb2_grpc = _import_grpc_deps()
        self._grpc = grpc
        self._pb2 = gossip_pb2
        self._pb2_grpc = gossip_pb2_grpc
        self._handler = handler

        servicer = _GossipServicer(handler, gossip_pb2, gossip_pb2_grpc)

        server = grpc.server(
            futures.ThreadPoolExecutor(max_workers=self._max_workers),
            options=[
                ("grpc.max_send_message_length", 60 * 1024 * 1024),
                ("grpc.max_receive_message_length", 60 * 1024 * 1024),
            ],
        )

        # Dynamically add servicer (avoids import-time dependency on stubs)
        adder = getattr(
            gossip_pb2_grpc,
            "add_GossipServiceServicer_to_server",
        )

        # Wrap servicer so it inherits the generated base class
        class BoundServicer(gossip_pb2_grpc.GossipServiceServicer):
            def ExchangeParameters(self_, request, context):
                return servicer.ExchangeParameters(request, context)

            def Ping(self_, request, context):
                return servicer.Ping(request, context)

        adder(BoundServicer(), server)
        server.add_insecure_port(f"{host}:{port}")
        server.start()
        self._server = server
        self._running = True
        logger.info("gRPC server listening on %s:%d", host, port)

    def stop_server(self) -> None:
        if self._server:
            self._server.stop(grace=5.0)
            self._server = None
        self._running = False
        logger.info("gRPC server stopped.")

    @property
    def is_running(self) -> bool:
        return self._running

    # ── Client ────────────────────────────────────────────────────────────────

    def send_parameters(
        self,
        peer_host: str,
        peer_port: int,
        payload: WirePayload,
        timeout: float = 15.0,
    ) -> WirePayload:
        grpc, gossip_pb2, gossip_pb2_grpc = _import_grpc_deps()
        addr = f"{peer_host}:{peer_port}"
        options = [
            ("grpc.max_send_message_length", 60 * 1024 * 1024),
            ("grpc.max_receive_message_length", 60 * 1024 * 1024),
        ]
        try:
            with grpc.insecure_channel(addr, options=options) as channel:
                stub = gossip_pb2_grpc.GossipServiceStub(channel)
                request = _to_pb(payload, gossip_pb2)
                response = stub.ExchangeParameters(request, timeout=timeout)
                return _from_pb(response)
        except grpc.RpcError as exc:
            raise TransportError(
                f"gRPC call to {addr} failed: {exc.code()} — {exc.details()}"
            ) from exc

    def ping(
        self,
        peer_host: str,
        peer_port: int,
        node_id: str,
        timeout: float = 5.0,
    ) -> bool:
        grpc, gossip_pb2, gossip_pb2_grpc = _import_grpc_deps()
        addr = f"{peer_host}:{peer_port}"
        try:
            with grpc.insecure_channel(addr) as channel:
                stub = gossip_pb2_grpc.GossipServiceStub(channel)
                response = stub.Ping(
                    gossip_pb2.PingRequest(node_id=node_id), timeout=timeout
                )
                return response.alive
        except grpc.RpcError:
            return False
