#!/usr/bin/env bash
# generate_proto.sh — Compile gossip.proto into Python gRPC stubs.
# Run from the repository root: bash scripts/generate_proto.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_DIR="${REPO_ROOT}/proto"
OUT_DIR="${REPO_ROOT}/src/bloomfl/generated"

echo "==> Generating gRPC stubs"
echo "    proto: ${PROTO_DIR}/gossip.proto"
echo "    out:   ${OUT_DIR}"

mkdir -p "${OUT_DIR}"

python -m grpc_tools.protoc \
    -I"${PROTO_DIR}" \
    --python_out="${OUT_DIR}" \
    --pyi_out="${OUT_DIR}" \
    --grpc_python_out="${OUT_DIR}" \
    "${PROTO_DIR}/gossip.proto"

# Fix absolute imports generated by protoc (make them relative-friendly)
# grpc_tools sometimes emits `import gossip_pb2 as gossip__pb2` which breaks
# when the file is inside a package.  Patch to use the package path.
sed -i 's/^import gossip_pb2 as gossip__pb2$/from bloomfl.generated import gossip_pb2 as gossip__pb2/' \
    "${OUT_DIR}/gossip_pb2_grpc.py" 2>/dev/null || true

echo "==> Done. Files generated:"
ls -1 "${OUT_DIR}"/*.py 2>/dev/null || echo "    (none — check for errors above)"
